/* sal.h - minimal SAL stub for building with the VC++ 2003 Toolkit and the
   Windows SDK headers from the Civ4 SDK installer. All annotations expand to nothing. */
#pragma once
#define __SAL_H_FULL_VER 140050727

#define __assume_ValidCompNameA(a0)
#define __assume_ValidCompNameW(a0)
#define __bcount(a0)
#define __bcount_opt(a0)
#define __blocksOn(a0)
#define __byte_readableTo(a0)
#define __byte_writableTo(a0)
#define __callback
#define __control_entrypoint(a0)
#define __data_entrypoint(a0)
#define __deref
#define __deref_bcount(a0)
#define __deref_bcount_opt(a0)
#define __deref_ecount(a0)
#define __deref_ecount_opt(a0)
#define __deref_inout
#define __deref_inout_bcount(a0)
#define __deref_inout_bcount_full(a0)
#define __deref_inout_bcount_full_opt(a0)
#define __deref_inout_bcount_nz(a0)
#define __deref_inout_bcount_nz_opt(a0)
#define __deref_inout_bcount_opt(a0)
#define __deref_inout_bcount_part(a0,a1)
#define __deref_inout_bcount_part_opt(a0,a1)
#define __deref_inout_bcount_z(a0)
#define __deref_inout_bcount_z_opt(a0)
#define __deref_inout_ecount(a0)
#define __deref_inout_ecount_full(a0)
#define __deref_inout_ecount_full_opt(a0)
#define __deref_inout_ecount_nz(a0)
#define __deref_inout_ecount_nz_opt(a0)
#define __deref_inout_ecount_opt(a0)
#define __deref_inout_ecount_part(a0,a1)
#define __deref_inout_ecount_part_opt(a0,a1)
#define __deref_inout_ecount_z(a0)
#define __deref_inout_ecount_z_opt(a0)
#define __deref_inout_nz
#define __deref_inout_nz_opt
#define __deref_inout_opt
#define __deref_inout_z
#define __deref_inout_z_opt
#define __deref_opt_bcount(a0)
#define __deref_opt_bcount_opt(a0)
#define __deref_opt_ecount(a0)
#define __deref_opt_ecount_opt(a0)
#define __deref_opt_inout
#define __deref_opt_inout_bcount(a0)
#define __deref_opt_inout_bcount_full(a0)
#define __deref_opt_inout_bcount_full_opt(a0)
#define __deref_opt_inout_bcount_nz(a0)
#define __deref_opt_inout_bcount_nz_opt(a0)
#define __deref_opt_inout_bcount_opt(a0)
#define __deref_opt_inout_bcount_part(a0,a1)
#define __deref_opt_inout_bcount_part_opt(a0,a1)
#define __deref_opt_inout_bcount_z(a0)
#define __deref_opt_inout_bcount_z_opt(a0)
#define __deref_opt_inout_ecount(a0)
#define __deref_opt_inout_ecount_full(a0)
#define __deref_opt_inout_ecount_full_opt(a0)
#define __deref_opt_inout_ecount_nz(a0)
#define __deref_opt_inout_ecount_nz_opt(a0)
#define __deref_opt_inout_ecount_opt(a0)
#define __deref_opt_inout_ecount_part(a0,a1)
#define __deref_opt_inout_ecount_part_opt(a0,a1)
#define __deref_opt_inout_ecount_z(a0)
#define __deref_opt_inout_ecount_z_opt(a0)
#define __deref_opt_inout_nz
#define __deref_opt_inout_nz_opt
#define __deref_opt_inout_opt
#define __deref_opt_inout_z
#define __deref_opt_inout_z_opt
#define __deref_opt_out
#define __deref_opt_out_bcount(a0)
#define __deref_opt_out_bcount_full(a0)
#define __deref_opt_out_bcount_full_opt(a0)
#define __deref_opt_out_bcount_nz_opt(a0)
#define __deref_opt_out_bcount_opt(a0)
#define __deref_opt_out_bcount_part(a0,a1)
#define __deref_opt_out_bcount_part_opt(a0,a1)
#define __deref_opt_out_bcount_z_opt(a0)
#define __deref_opt_out_ecount(a0)
#define __deref_opt_out_ecount_full(a0)
#define __deref_opt_out_ecount_full_opt(a0)
#define __deref_opt_out_ecount_nz_opt(a0)
#define __deref_opt_out_ecount_opt(a0)
#define __deref_opt_out_ecount_part(a0,a1)
#define __deref_opt_out_ecount_part_opt(a0,a1)
#define __deref_opt_out_ecount_z_opt(a0)
#define __deref_opt_out_nz_opt
#define __deref_opt_out_opt
#define __deref_opt_out_z_opt
#define __deref_out
#define __deref_out_bcount(a0)
#define __deref_out_bcount_full(a0)
#define __deref_out_bcount_full_opt(a0)
#define __deref_out_bcount_nz(a0)
#define __deref_out_bcount_nz_opt(a0)
#define __deref_out_bcount_opt(a0)
#define __deref_out_bcount_part(a0,a1)
#define __deref_out_bcount_part_opt(a0,a1)
#define __deref_out_bcount_z(a0)
#define __deref_out_bcount_z_opt(a0)
#define __deref_out_ecount(a0)
#define __deref_out_ecount_full(a0)
#define __deref_out_ecount_full_opt(a0)
#define __deref_out_ecount_nz(a0)
#define __deref_out_ecount_nz_opt(a0)
#define __deref_out_ecount_opt(a0)
#define __deref_out_ecount_part(a0,a1)
#define __deref_out_ecount_part_opt(a0,a1)
#define __deref_out_ecount_z(a0)
#define __deref_out_ecount_z_opt(a0)
#define __deref_out_nz
#define __deref_out_nz_opt
#define __deref_out_opt
#define __deref_out_z
#define __deref_out_z_opt
#define __ecount(a0)
#define __ecount_opt(a0)
#define __elem_readableTo(a0)
#define __elem_writableTo(a0)
#define __exceptthat
#define __fallthrough(a0)
#define __format_string
#define __in
#define __in_bcount(a0)
#define __in_bcount_nz(a0)
#define __in_bcount_nz_opt(a0)
#define __in_bcount_opt(a0)
#define __in_bcount_z(a0)
#define __in_bcount_z_opt(a0)
#define __in_ecount(a0)
#define __in_ecount_nz(a0)
#define __in_ecount_nz_opt(a0)
#define __in_ecount_opt(a0)
#define __in_ecount_z(a0)
#define __in_ecount_z_opt(a0)
#define __in_nz
#define __in_nz_opt
#define __in_opt
#define __in_z
#define __in_z_opt
#define __inner_blocksOn
#define __inner_callback
#define __inner_checkReturn
#define __inner_control_entrypoint(a0)
#define __inner_data_entrypoint
#define __inner_fallthrough
#define __inner_fallthrough_dec
#define __inner_override
#define __inner_success
#define __inner_typefix
#define __inout
#define __inout_bcount(a0)
#define __inout_bcount_full(a0)
#define __inout_bcount_full_opt(a0)
#define __inout_bcount_nz(a0)
#define __inout_bcount_nz_opt(a0)
#define __inout_bcount_opt(a0)
#define __inout_bcount_part(a0,a1)
#define __inout_bcount_part_opt(a0,a1)
#define __inout_bcount_z(a0)
#define __inout_bcount_z_opt(a0)
#define __inout_ecount(a0)
#define __inout_ecount_full(a0)
#define __inout_ecount_full_opt(a0)
#define __inout_ecount_nz(a0)
#define __inout_ecount_nz_opt(a0)
#define __inout_ecount_opt(a0)
#define __inout_ecount_part(a0,a1)
#define __inout_ecount_part_opt(a0,a1)
#define __inout_ecount_z(a0)
#define __inout_ecount_z_opt(a0)
#define __inout_nz
#define __inout_nz_opt
#define __inout_opt
#define __inout_z
#define __inout_z_opt
#define __maybenull
#define __maybereadonly
#define __maybevalid
#define __notnull
#define __notreadonly
#define __notvalid
#define __null
#define __nullterminated
#define __out
#define __out_bcount(a0)
#define __out_bcount_full(a0)
#define __out_bcount_full_opt(a0)
#define __out_bcount_nz(a0)
#define __out_bcount_nz_opt(a0)
#define __out_bcount_opt(a0)
#define __out_bcount_part(a0,a1)
#define __out_bcount_part_opt(a0,a1)
#define __out_bcount_z(a0)
#define __out_bcount_z_opt(a0)
#define __out_ecount(a0)
#define __out_ecount_full(a0)
#define __out_ecount_full_opt(a0)
#define __out_ecount_nz(a0)
#define __out_ecount_nz_opt(a0)
#define __out_ecount_opt(a0)
#define __out_ecount_part(a0,a1)
#define __out_ecount_part_opt(a0,a1)
#define __out_ecount_z(a0)
#define __out_ecount_z_opt(a0)
#define __out_nz
#define __out_nz_opt
#define __out_opt
#define __out_z
#define __override
#define __post
#define __postcond
#define __pre
#define __precond(a0)
#define __readableTo(a0)
#define __readonly
#define __refparam
#define __reserved
#define __success(a0)
#define __typefix(a0)
#define __valid
#define __writableTo(a0)
